build: Fix deprecated-non-prototype error on C2x build
macOS 13.6.3 comes with C2x:

> Apple clang version 15.0.0 (clang-1500.1.0.2.5)
> Target: arm64-apple-darwin22.6.0
> Thread model: posix

Without this patch, `make` fails:

```
main.c:177:23: error: passing arguments to 'new_client_data' without a
prototype is deprecated in all versions of C
and is not supported in C2x [-Werror,-Wdeprecated-non-prototype]
        cli = new_client_data( fd );
                             ^
1 error generated.
```

Note that `-Wdeprecated-non-prototype` can't be used (yet) since
GNU gcc from Debian Buster doesn't recognise the option yet:

```
gcc: error: unrecognized command line option ‘-Wdeprecated-non-prototype’;
```

Although per https://github.com/llvm/llvm-project/commit/11da1b53d8,
one could use `-Wno-strict-prototypes` to disable the pre-existing
superset instead, which should pass on both old and newer versions.

Change-Id: Ib3144f4f282b01c0e98c10727f7dbd195940c2f8