Support compiling on Darwin/BSD
Fix various compiler errors.

```
./locks.h:37:2: error: expected identifier
  WAIT_ANY,    // Waiting on ACQ4ANY
```

```
client_data.c:6:10: fatal error: 'malloc.h' file not found
```

```
locks.c:183:4: error: implicit declaration of function 'timerisset' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  time_stats( to_notify, waiting_time_for_good );
  ^
./stats.h:43:9: note: expanded from macro 'time_stats'
  if ( !timerisset( &now ) ) { \
        ^
```

On macOS 10.15, sys/time.h expands to this one:
https://opensource.apple.com/source/xnu/xnu-6153.141.1/bsd/sys/time.h.auto.html
which to comply with the fact that timerisset isn't part of POSIX actually
excludes it when _POSIX_C_SOURCE is set, but can be opted back into
by setting _DARWIN_C_SOURCE.

Change-Id: Ic630ddbceb5111d714c708e6e4ba014ca0c77172